Create backup.sh
hyunchan-park/jcloud pull request #9
Opened 2021-10-14 15:37 UTC by ginami0129

특정 프로젝트에 포함된 인스턴스들에 대한 정기적인 백업 서비스 구축 스크립트 초안 작성했습니다.

2021-11-24 01:43 UTC, hyunchan-park requested changes

2021-11-24 01:43 UTC, hyunchan-park commented on backup.sh
> +readonly SSH_PROT=7777
PROT -> PORT 오타 인것 같습니다.

2021-11-24 01:43 UTC, hyunchan-park commented on backup.sh
> +readonly SSH_CLIENT='root@203.254.143.173'
IP 주소를 별도의 변수로 관리하는게 좋겠습니다.

2021-11-24 01:43 UTC, hyunchan-park commented on backup.sh
> +readonly BANDWIDTH_LIMIT=50000
별도의 readme 가 있어야 할 것 같고,
왜 이런 변수들을 사용하는지, 왜 대역폭 제한이 있어야 하는지를 
문서로 설명해두는게 좋겠습니다.

2021-11-24 01:43 UTC, hyunchan-park commented on backup.sh
> +
.env (환경변수파일) 나 openrc 같은 pre-requirements 들에 대한 언급이 필요해보입니다.
readme 에서 상세히 설명하고 여기서는 간단하게 주석에 남겨두면 좋겠습니다.
openrc 같은 경우에는 간단하니까 여기다 아예 옮겨놓는것도 괜찮을것 같습니다.

2021-11-24 08:36 UTC, ginami0129g commented on backup.sh
> +readonly SSH_PROT=7777
네 'PORT'로 수정했습니다!

2021-11-24 08:36 UTC, ginami0129g commented on backup.sh
> +readonly SSH_CLIENT='root@203.254.143.173'
IP 주소 및 실행 환경에 따라서 달라지는 변수들을 .env 파일에 별도로 작성하였습니다.

2021-11-24 08:46 UTC, ginami0129g commented on backup.sh
> +readonly BANDWIDTH_LIMIT=50000
왜 이런 변수들을 사용하는지에 대해 .env 파일 설명 하는 부분에 추가하였습니다.
왜 대역폭 제한이 있어야 하는지에 대해 특징 부분에 추가하였습니다.

2021-11-24 09:43 UTC, ginami0129g commented on backup.sh
> +
환경 변수 설명 부분에 추가하였습니다. 
openrc 를 여기에 옮기려고 시도 했으나 내부적으로 source 명령어를 devstack 설치 경로에 종속적으로 수행하는 것을 확인 했습니다. 추가적인 확인이 필요할 것 같습니다.

2021-11-24 09:49 UTC, ginami0129g commented
backup.sh에 대한 설명 문서, .env 파일로 환경 변수를 관리 하도록 추가했습니다. 확인 부탁드립니다.

2021-11-25 01:27 UTC, hyunchan-park requested changes

2021-11-25 01:27 UTC, hyunchan-park commented on backup.sh
>      for ((i = 0; i < $(($((${#snapshot[@]})) - 5)); i++)); do
여기 5를 변수로 처리하는게 좋을것 같습니다.

2021-11-25 05:55 UTC, ginami0129g commented on backup.sh
>      for ((i = 0; i < $(($((${#snapshot[@]})) - 5)); i++)); do
넵 MAX_COUNT_OF_SNAPSHOT라는 이름으로 환경변수에 추가했고 관련 문서 업데이트 하였습니다.

2023-08-29 17:46 UTC, merged